/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TechRadarRouteImport } from './routes/tech-radar'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TeamWorkflowRouteImport } from './routes/team-workflow'
import { Route as TeamPerformanceRouteImport } from './routes/team-performance'
import { Route as TeamMapRouteImport } from './routes/team-map'
import { Route as ResponsibilityChartRouteImport } from './routes/responsibility-chart'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as ProjectRecoveryRouteImport } from './routes/project-recovery'
import { Route as ProjectProgressRouteImport } from './routes/project-progress'
import { Route as PmPerformanceRouteImport } from './routes/pm-performance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveWorkRouteImport } from './routes/live-work'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DevPerformanceRouteImport } from './routes/dev-performance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiRecruitmentInstructionsRouteImport } from './routes/api.recruitment.instructions'
import { Route as ApiRecruitmentCandidatesRouteImport } from './routes/api.recruitment.candidates'
import { Route as ApiPerformanceEmailDispatchRouteImport } from './routes/api.performance-email.dispatch'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRadarRoute = TechRadarRouteImport.update({
  id: '/tech-radar',
  path: '/tech-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamWorkflowRoute = TeamWorkflowRouteImport.update({
  id: '/team-workflow',
  path: '/team-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamPerformanceRoute = TeamPerformanceRouteImport.update({
  id: '/team-performance',
  path: '/team-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMapRoute = TeamMapRouteImport.update({
  id: '/team-map',
  path: '/team-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibilityChartRoute = ResponsibilityChartRouteImport.update({
  id: '/responsibility-chart',
  path: '/responsibility-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRecoveryRoute = ProjectRecoveryRouteImport.update({
  id: '/project-recovery',
  path: '/project-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProgressRoute = ProjectProgressRouteImport.update({
  id: '/project-progress',
  path: '/project-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PmPerformanceRoute = PmPerformanceRouteImport.update({
  id: '/pm-performance',
  path: '/pm-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveWorkRoute = LiveWorkRouteImport.update({
  id: '/live-work',
  path: '/live-work',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPerformanceRoute = DevPerformanceRouteImport.update({
  id: '/dev-performance',
  path: '/dev-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecruitmentInstructionsRoute =
  ApiRecruitmentInstructionsRouteImport.update({
    id: '/api/recruitment/instructions',
    path: '/api/recruitment/instructions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRecruitmentCandidatesRoute =
  ApiRecruitmentCandidatesRouteImport.update({
    id: '/api/recruitment/candidates',
    path: '/api/recruitment/candidates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPerformanceEmailDispatchRoute =
  ApiPerformanceEmailDispatchRouteImport.update({
    id: '/api/performance-email/dispatch',
    path: '/api/performance-email/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-performance': typeof DevPerformanceRoute
  '/domains': typeof DomainsRoute
  '/live-work': typeof LiveWorkRoute
  '/login': typeof LoginRoute
  '/pm-performance': typeof PmPerformanceRoute
  '/project-progress': typeof ProjectProgressRoute
  '/project-recovery': typeof ProjectRecoveryRoute
  '/recruitment': typeof RecruitmentRoute
  '/responsibility-chart': typeof ResponsibilityChartRoute
  '/team-map': typeof TeamMapRoute
  '/team-performance': typeof TeamPerformanceRoute
  '/team-workflow': typeof TeamWorkflowRoute
  '/teams': typeof TeamsRoute
  '/tech-radar': typeof TechRadarRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/performance-email/dispatch': typeof ApiPerformanceEmailDispatchRoute
  '/api/recruitment/candidates': typeof ApiRecruitmentCandidatesRoute
  '/api/recruitment/instructions': typeof ApiRecruitmentInstructionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-performance': typeof DevPerformanceRoute
  '/domains': typeof DomainsRoute
  '/live-work': typeof LiveWorkRoute
  '/login': typeof LoginRoute
  '/pm-performance': typeof PmPerformanceRoute
  '/project-progress': typeof ProjectProgressRoute
  '/project-recovery': typeof ProjectRecoveryRoute
  '/recruitment': typeof RecruitmentRoute
  '/responsibility-chart': typeof ResponsibilityChartRoute
  '/team-map': typeof TeamMapRoute
  '/team-performance': typeof TeamPerformanceRoute
  '/team-workflow': typeof TeamWorkflowRoute
  '/teams': typeof TeamsRoute
  '/tech-radar': typeof TechRadarRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/performance-email/dispatch': typeof ApiPerformanceEmailDispatchRoute
  '/api/recruitment/candidates': typeof ApiRecruitmentCandidatesRoute
  '/api/recruitment/instructions': typeof ApiRecruitmentInstructionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev-performance': typeof DevPerformanceRoute
  '/domains': typeof DomainsRoute
  '/live-work': typeof LiveWorkRoute
  '/login': typeof LoginRoute
  '/pm-performance': typeof PmPerformanceRoute
  '/project-progress': typeof ProjectProgressRoute
  '/project-recovery': typeof ProjectRecoveryRoute
  '/recruitment': typeof RecruitmentRoute
  '/responsibility-chart': typeof ResponsibilityChartRoute
  '/team-map': typeof TeamMapRoute
  '/team-performance': typeof TeamPerformanceRoute
  '/team-workflow': typeof TeamWorkflowRoute
  '/teams': typeof TeamsRoute
  '/tech-radar': typeof TechRadarRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/api/performance-email/dispatch': typeof ApiPerformanceEmailDispatchRoute
  '/api/recruitment/candidates': typeof ApiRecruitmentCandidatesRoute
  '/api/recruitment/instructions': typeof ApiRecruitmentInstructionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-performance'
    | '/domains'
    | '/live-work'
    | '/login'
    | '/pm-performance'
    | '/project-progress'
    | '/project-recovery'
    | '/recruitment'
    | '/responsibility-chart'
    | '/team-map'
    | '/team-performance'
    | '/team-workflow'
    | '/teams'
    | '/tech-radar'
    | '/users'
    | '/projects/$projectId'
    | '/api/performance-email/dispatch'
    | '/api/recruitment/candidates'
    | '/api/recruitment/instructions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-performance'
    | '/domains'
    | '/live-work'
    | '/login'
    | '/pm-performance'
    | '/project-progress'
    | '/project-recovery'
    | '/recruitment'
    | '/responsibility-chart'
    | '/team-map'
    | '/team-performance'
    | '/team-workflow'
    | '/teams'
    | '/tech-radar'
    | '/users'
    | '/projects/$projectId'
    | '/api/performance-email/dispatch'
    | '/api/recruitment/candidates'
    | '/api/recruitment/instructions'
  id:
    | '__root__'
    | '/'
    | '/dev-performance'
    | '/domains'
    | '/live-work'
    | '/login'
    | '/pm-performance'
    | '/project-progress'
    | '/project-recovery'
    | '/recruitment'
    | '/responsibility-chart'
    | '/team-map'
    | '/team-performance'
    | '/team-workflow'
    | '/teams'
    | '/tech-radar'
    | '/users'
    | '/projects/$projectId'
    | '/api/performance-email/dispatch'
    | '/api/recruitment/candidates'
    | '/api/recruitment/instructions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevPerformanceRoute: typeof DevPerformanceRoute
  DomainsRoute: typeof DomainsRoute
  LiveWorkRoute: typeof LiveWorkRoute
  LoginRoute: typeof LoginRoute
  PmPerformanceRoute: typeof PmPerformanceRoute
  ProjectProgressRoute: typeof ProjectProgressRoute
  ProjectRecoveryRoute: typeof ProjectRecoveryRoute
  RecruitmentRoute: typeof RecruitmentRoute
  ResponsibilityChartRoute: typeof ResponsibilityChartRoute
  TeamMapRoute: typeof TeamMapRoute
  TeamPerformanceRoute: typeof TeamPerformanceRoute
  TeamWorkflowRoute: typeof TeamWorkflowRoute
  TeamsRoute: typeof TeamsRoute
  TechRadarRoute: typeof TechRadarRoute
  UsersRoute: typeof UsersRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ApiPerformanceEmailDispatchRoute: typeof ApiPerformanceEmailDispatchRoute
  ApiRecruitmentCandidatesRoute: typeof ApiRecruitmentCandidatesRoute
  ApiRecruitmentInstructionsRoute: typeof ApiRecruitmentInstructionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-radar': {
      id: '/tech-radar'
      path: '/tech-radar'
      fullPath: '/tech-radar'
      preLoaderRoute: typeof TechRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-workflow': {
      id: '/team-workflow'
      path: '/team-workflow'
      fullPath: '/team-workflow'
      preLoaderRoute: typeof TeamWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-performance': {
      id: '/team-performance'
      path: '/team-performance'
      fullPath: '/team-performance'
      preLoaderRoute: typeof TeamPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-map': {
      id: '/team-map'
      path: '/team-map'
      fullPath: '/team-map'
      preLoaderRoute: typeof TeamMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsibility-chart': {
      id: '/responsibility-chart'
      path: '/responsibility-chart'
      fullPath: '/responsibility-chart'
      preLoaderRoute: typeof ResponsibilityChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-recovery': {
      id: '/project-recovery'
      path: '/project-recovery'
      fullPath: '/project-recovery'
      preLoaderRoute: typeof ProjectRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-progress': {
      id: '/project-progress'
      path: '/project-progress'
      fullPath: '/project-progress'
      preLoaderRoute: typeof ProjectProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pm-performance': {
      id: '/pm-performance'
      path: '/pm-performance'
      fullPath: '/pm-performance'
      preLoaderRoute: typeof PmPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-work': {
      id: '/live-work'
      path: '/live-work'
      fullPath: '/live-work'
      preLoaderRoute: typeof LiveWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-performance': {
      id: '/dev-performance'
      path: '/dev-performance'
      fullPath: '/dev-performance'
      preLoaderRoute: typeof DevPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recruitment/instructions': {
      id: '/api/recruitment/instructions'
      path: '/api/recruitment/instructions'
      fullPath: '/api/recruitment/instructions'
      preLoaderRoute: typeof ApiRecruitmentInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recruitment/candidates': {
      id: '/api/recruitment/candidates'
      path: '/api/recruitment/candidates'
      fullPath: '/api/recruitment/candidates'
      preLoaderRoute: typeof ApiRecruitmentCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/performance-email/dispatch': {
      id: '/api/performance-email/dispatch'
      path: '/api/performance-email/dispatch'
      fullPath: '/api/performance-email/dispatch'
      preLoaderRoute: typeof ApiPerformanceEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevPerformanceRoute: DevPerformanceRoute,
  DomainsRoute: DomainsRoute,
  LiveWorkRoute: LiveWorkRoute,
  LoginRoute: LoginRoute,
  PmPerformanceRoute: PmPerformanceRoute,
  ProjectProgressRoute: ProjectProgressRoute,
  ProjectRecoveryRoute: ProjectRecoveryRoute,
  RecruitmentRoute: RecruitmentRoute,
  ResponsibilityChartRoute: ResponsibilityChartRoute,
  TeamMapRoute: TeamMapRoute,
  TeamPerformanceRoute: TeamPerformanceRoute,
  TeamWorkflowRoute: TeamWorkflowRoute,
  TeamsRoute: TeamsRoute,
  TechRadarRoute: TechRadarRoute,
  UsersRoute: UsersRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ApiPerformanceEmailDispatchRoute: ApiPerformanceEmailDispatchRoute,
  ApiRecruitmentCandidatesRoute: ApiRecruitmentCandidatesRoute,
  ApiRecruitmentInstructionsRoute: ApiRecruitmentInstructionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
