/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TechRadarRouteImport } from './routes/tech-radar'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TeamWorkflowRouteImport } from './routes/team-workflow'
import { Route as TeamMapRouteImport } from './routes/team-map'
import { Route as ResponsibilityChartRouteImport } from './routes/responsibility-chart'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRadarRoute = TechRadarRouteImport.update({
  id: '/tech-radar',
  path: '/tech-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamWorkflowRoute = TeamWorkflowRouteImport.update({
  id: '/team-workflow',
  path: '/team-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamMapRoute = TeamMapRouteImport.update({
  id: '/team-map',
  path: '/team-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibilityChartRoute = ResponsibilityChartRouteImport.update({
  id: '/responsibility-chart',
  path: '/responsibility-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/responsibility-chart': typeof ResponsibilityChartRoute
  '/team-map': typeof TeamMapRoute
  '/team-workflow': typeof TeamWorkflowRoute
  '/teams': typeof TeamsRoute
  '/tech-radar': typeof TechRadarRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/responsibility-chart': typeof ResponsibilityChartRoute
  '/team-map': typeof TeamMapRoute
  '/team-workflow': typeof TeamWorkflowRoute
  '/teams': typeof TeamsRoute
  '/tech-radar': typeof TechRadarRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/responsibility-chart': typeof ResponsibilityChartRoute
  '/team-map': typeof TeamMapRoute
  '/team-workflow': typeof TeamWorkflowRoute
  '/teams': typeof TeamsRoute
  '/tech-radar': typeof TechRadarRoute
  '/users': typeof UsersRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domains'
    | '/login'
    | '/responsibility-chart'
    | '/team-map'
    | '/team-workflow'
    | '/teams'
    | '/tech-radar'
    | '/users'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/domains'
    | '/login'
    | '/responsibility-chart'
    | '/team-map'
    | '/team-workflow'
    | '/teams'
    | '/tech-radar'
    | '/users'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/domains'
    | '/login'
    | '/responsibility-chart'
    | '/team-map'
    | '/team-workflow'
    | '/teams'
    | '/tech-radar'
    | '/users'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainsRoute: typeof DomainsRoute
  LoginRoute: typeof LoginRoute
  ResponsibilityChartRoute: typeof ResponsibilityChartRoute
  TeamMapRoute: typeof TeamMapRoute
  TeamWorkflowRoute: typeof TeamWorkflowRoute
  TeamsRoute: typeof TeamsRoute
  TechRadarRoute: typeof TechRadarRoute
  UsersRoute: typeof UsersRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-radar': {
      id: '/tech-radar'
      path: '/tech-radar'
      fullPath: '/tech-radar'
      preLoaderRoute: typeof TechRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-workflow': {
      id: '/team-workflow'
      path: '/team-workflow'
      fullPath: '/team-workflow'
      preLoaderRoute: typeof TeamWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-map': {
      id: '/team-map'
      path: '/team-map'
      fullPath: '/team-map'
      preLoaderRoute: typeof TeamMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsibility-chart': {
      id: '/responsibility-chart'
      path: '/responsibility-chart'
      fullPath: '/responsibility-chart'
      preLoaderRoute: typeof ResponsibilityChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainsRoute: DomainsRoute,
  LoginRoute: LoginRoute,
  ResponsibilityChartRoute: ResponsibilityChartRoute,
  TeamMapRoute: TeamMapRoute,
  TeamWorkflowRoute: TeamWorkflowRoute,
  TeamsRoute: TeamsRoute,
  TechRadarRoute: TechRadarRoute,
  UsersRoute: UsersRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
